### ISSUE TITLE
consider moving attribute access to a sub-object

### ISSUE THREAD

**Issue by tomjnixon** [tomjnixon/yarp#10]
For example, instead of writing

```python
>>> v = Value(1j)
>>> v.real
Value(0.0)
```

It might be:

```python
>>> v.attrs.real
Value(0.0)
```

Advantages of this change:

- plain attribute access restricts the design -- adding more methods or attributes may break existing code which uses plain attribute access with the same name
- plain attribute access can make for confusing error messages if Value methods are mistyped:
  ```python
  >>> Value().on_change
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/home/tom/dev/yarp/yarp/function_wrappers.py", line 77, in wrapped
      return Value(inputs=inputs, get_value=get_value)
    File "/home/tom/dev/yarp/yarp/value.py", line 193, in __init__
      self._on_inputs_done()
    File "/home/tom/dev/yarp/yarp/value.py", line 247, in _on_inputs_done
      new_value = self._get_value()
    File "/home/tom/dev/yarp/yarp/function_wrappers.py", line 75, in get_value
      return f(*arg_values, **kwarg_values)
  AttributeError: '_Sentinel' object has no attribute 'on_change'
  ```
  this could probably be tidied up, but it just makes it even more confusing when it happens deep in some asyncio mess.
- plain attribute access feels like it might lead to some odd things accidentally working when they shouldn't, or feeling broken -- e.g. some methods like `__int__` are propagated when they don't really make sense.

The main disadvantage of changing is that it makes it less likely that Values will just work in normal code. On the other hand, the code that this would work with is very limited, and you'd be better off using `fn` anyway.

**Comment by tomjnixon** [comment]
Just got bit by this again:

```python
async def event_listen(path, client):
    event = yarp.Event()
    await client.event_listen_cb(path, event.emit_event)
    return event
```

`emit_event` should just `emit`, but results in another `Event`, and because `__call__` is wrapped too, when the callback is called, nothing happens

i definitely want to move some of this into a proxy, probably attribute access and calling (or just remove them and use functions)

**Comment by tomjnixon** [comment]
Just got bit by this again:

```python
    delayed = delay(v, dv)
    q = asyncio.Queue()
    delayed.on_event(q.put_nowait)

    await asyncio.sleep(0.1)

    assert delayed.get_nowait() == 2
```

The assert of course should have been on `q.get_nowait()`, but this passes.
